# If you change this file in a Merge Request, please also create
# a MR on https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests

defaults: &defaults
  gitlab_server:
    url: '{{GITLAB_URL}}' # Replace with your gitlab server url
    app_id: '{{GITLAB_APP_ID}}'
    app_secret: '{{GITLAB_APP_SECRET}}'

  ## Gitlab CI settings
  gitlab_ci:
    ## Web server settings
    host: "{{GITLAB_CI_HOST}}"
    port: {{GITLAB_CI_PORT}}
    https: {{GITLAB_CI_HTTPS}}

    ## Email settings
    # Email address used in the "From" field in mails sent by GitLab-CI
    email_from: "{{GITLAB_CI_EMAIL}}"

    # Email address of your support contact (default: same as email_from)
    support_email: "{{GITLAB_CI_SUPPORT}}"

    # Default project notifications settings:
    #
    # Send emails only on broken builds (default: true)
    all_broken_builds: {{GITLAB_CI_NOTIFY_ON_BROKEN_BUILDS}}
    #
    # Add pusher to recipients list (default: false)
    add_pusher: {{GITLAB_CI_NOTIFY_PUSHER}}

    # The location where build traces are stored (default: builds/). Relative paths are relative to Rails.root
    builds_path: "{{GITLAB_CI_BUILDS_DIR}}"

  gravatar:
    enabled: true
    plain_url: "http://www.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"
    ssl_url:   "https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"

  ## Backup settings
  backup:
    path: "{{GITLAB_CI_BACKUP_DIR}}"   # Relative paths are relative to Rails.root (default: tmp/backups/)
    keep_time: {{GITLAB_CI_BACKUP_EXPIRY}}   # default: 0 (forever) (in seconds)
    upload:
      # Fog storage connection settings, see http://fog.io/storage/ .
      connection:
        provider: AWS
        region: {{AWS_BACKUP_REGION}}
        aws_access_key_id: {{AWS_BACKUP_ACCESS_KEY_ID}}
        aws_secret_access_key: '{{AWS_BACKUP_SECRET_ACCESS_KEY}}'
      # The remote 'directory' to store your backups. For S3, this would be the bucket name.
      remote_directory: '{{AWS_BACKUP_BUCKET}}'
    #   # Use multipart uploads when file size reaches 100MB, see
    #   #  http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html
    #   multipart_chunk_size: 104857600


development:
  <<: *defaults

test:
  <<: *defaults
  gitlab_server:
    url: '{{GITLAB_URL}}'
    app_id: '{{GITLAB_APP_ID}}'
    app_secret: '{{GITLAB_APP_SECRET}}'
  gitlab_ci:
    host: "{{GITLAB_CI_HOST}}"
    port: {{GITLAB_CI_PORT}}
    https: {{GITLAB_CI_HTTPS}}

production:
  <<: *defaults
