defaults: &defaults
  allowed_gitlab_urls:
    # Replace with your gitlab server url
    - '{{GITLAB_URL}}'

  ## Gitlab CI settings
  gitlab_ci:
    ## Web server settings
    host: {{GITLAB_CI_HOST}}
    port: {{GITLAB_CI_PORT}}
    https: {{GITLAB_CI_HTTPS}}

    ## Email settings
    # Email address used in the "From" field in mails sent by GitLab-CI
    email_from: {{GITLAB_CI_EMAIL}}

    # Email address of your support contact (default: same as email_from)
    support_email: {{GITLAB_CI_SUPPORT}}

    # Default project notifications settings:
    #
    # Send emails only on broken builds (default: true)
    # all_broken_builds: true
    #
    # Add committer to recipients list (default: false)
    # add_committer: true

  gravatar:
    enabled: true
    plain_url: "http://www.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"
    ssl_url:   "https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"


development:
  <<: *defaults

test:
  <<: *defaults
  allowed_gitlab_urls:
    - '{{GITLAB_URL}}'

production:
  <<: *defaults
