postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab_ci
    - DB_PASS=password
    - DB_NAME=gitlab_ci_production
  volumes:
    - /srv/docker/gitlab-ci/postgresql:/var/lib/postgresql
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab-ci/redis:/var/lib/redis
ci:
  image: sameersbn/gitlab-ci:7.10.2
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10081:80"
  environment:
    - GITLAB_CI_PORT=10081
    - GITLAB_CI_HOST=ci.damagehead.com
    - GITLAB_URL=https://git.damagehead.com
    - GITLAB_APP_ID=XXXX
    - GITLAB_APP_SECRET=YYYY
  volumes:
    - /srv/docker/gitlab-ci/gitlab-ci:/home/gitlab_ci/data
